- name: mysql configuration
  hosts: mysql
  become: yes
  tasks:
  - name: install MySQL server
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start MySQL server
    ansible.builtin.server:
      name: mysql-server
      state: started
      enabled: yes
